[package]
name = "cubing"
version = "0.2.0"
authors = ["Lucas Garron <code@garron.net"]
edition = "2021"
description = "Features from `cubing.js` in Rust."
homepage = "https://github.com/cubing/cubing.rs"
repository = "https://github.com/cubing/cubing.rs"
documentation = "https://github.com/cubing/cubing.rs"
keywords = ["cubing", "puzzle", "rubik", "solving", "WCA"]
license = "GPL-3.0-or-later"
readme = "README.md"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
lazy_static = "1.4.0"
nom = "7.1.3"
rand = "0.8.5"
regex = "1.7.1"
serde = { version = "1.0.154", features = ["derive", "rc"] }
serde_json = "1.0.94"

[[bin]]
name = "f2lfast"
path = "bin/f2lfast/main.rs"
