[workspace]
resolver = "2"

members = [
  "cubing",
  "cubing_core",
  "cubing_macros",
]
default-members = [
  "cubing"
]

[workspace.package]
version = "0.11.1"
license = "MPL-2.0"
edition = "2021"
