[package]
name = "cubing"
version = "0.5.3"
authors = ["Lucas Garron <code@garron.net"]
edition = "2021"
description = "Features from `cubing.js` in Rust."
homepage = "https://github.com/cubing/cubing.rs"
repository = "https://github.com/cubing/cubing.rs"
documentation = "https://github.com/cubing/cubing.rs"
keywords = ["cubing", "puzzle", "rubik", "solving", "WCA"]
license = "GPL-3.0-or-later"
readme = "README.md"

[dependencies]
derive_more = "0.99.17"
nom = "7.1.3"
serde = { version = "1.0.154", features = ["derive", "rc"] }
serde_json = "1.0.94"

[dev-dependencies]
clap = { version = "4.1.8", features = ["derive"] }
once_cell = "1.18.0"
rand = "0.8.5"
url = "2.3.1"

[[example]]
name = "f2lfast"
