name: CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: cargo-bins/cargo-binstall@v1.4.9
      - run: cargo binstall --no-confirm cargo-run-bin
      - run: make build
      - run: make test
      - run: make lint
